@startuml Sistema de reservas para cine

class Asiento {

    - Estado : boolean
    + Asiento ()
    + LiberarAsiento() : void
    + ReservarAsiento() : void
    + MostrarEstado() : String
}

class Sala{
    - SalaC : Arraylist<Arraylist<Asiento>>
    + Sala(filas : int, columnas : int)
    + LiberarAsiento(fila : int, columna : int) : void
    + ReservarAsiento(fila : int, columna : int) : void
    + MostrarEstado() : void
}

class Cine{
    - CineC : Arraylist<Arraylist<Sala>>
    + Cine(funciones : int, salas : int, filas : int, columnas : int)
    + LiberarAsiento(sala : int, funcion : int, fila : int, columna : int) : void
    + ReservarAsiento(sala : int, funcion : int, fila : int, columna : int) : void
    + MostrarEstado(sala : int, funcion : int) : void
}

class Reserva {
    - Scanner : Scanner
    + main(String[] args) : void
    + LimpiarConsola() : void
}

class Cancelaciones{
    - CancelacionesC = Stack <String>
    + Cancelaciones()
    + AgregarCancelaciones(funciones : int, salas : int, filas : int, columnas : int) : void
    + DeshacerCancelacion() : void
    + MostrarCancelaciones() : void
}

class Espera{
    - EsperaC = Queue <String>
    + Espera()
    + AgregarEspera(funciones : int, salas : int, filas : int, columnas : int) : void
    + DeshacerEspera() : void
    + MostrarEspera() : void
}

Cine *--- Sala
Sala *--- Asiento
Reserva ..> Cine : crea >
Cancelaciones --|> Cine : extiende >

@enduml
